Improvements and bug fixes of the ocl version: - In many places in the code size_t arguments were passed to kernels as cl_long, which caused complete failure of 32-bit version. This was not realized before due to lack of 32-bit system with modern GPU. Now corresponding type, named in_sizet (equal to either cl_uint or cl_ulong) is chosen during ADDA compilation, and is further passed to compiler of ocl sources. - optimized (cached) transpose kernels are not applicable to small problem sizes. That's why adda_ocl failed for box size<=4 (gridY<16 or gridZ<16). This is fixed by implementing fallback to non-cached kernel for small problems. - indexing of cc_sqrt in kernels was wrong, causing adda_ocl to produce wrong results for inhomogeneous scatterers (e.g. coated). It was fixed. - ndcomp is now cl_char instead of cl_long. - mat (private variable) in kernels is now uchar instead of char. - syntax of kernel transposeo was changed to be consistent with the rest of the code.
tests/2exec/comp2exec was updated, adding several ignores for ocl_seq mode. Current version of ADDA passes this test both on 32-bit and 64-bit Windows. There are only couple of trivial diffs: for -store_granul and -V. This can be considered a major milestone in development of adda_ocl.

Minor changes in parbas.h.

diff --git a/tests/2exec/comp2exec b/tests/2exec/comp2exec
--- a/tests/2exec/comp2exec
+++ b/tests/2exec/comp2exec
@@ -96,59 +96,63 @@ function mycmp {
   
   # First, set default numerical accuracy or adjust it based on cmdline
   if [[ $cmdline =~ "-granul " ]]; then
-	asmin atol 1
-	asmin rtol 2
+    asmin atol 1
+    asmin rtol 2
   else
     asmin atol 15
-	asmin rtol 8
+    asmin rtol 8
   fi
   # behavior is mainly determined by file name
   base=`basename $1`
   if [ "$base" == $SONAME ]; then
     # 2nd and 3rd parts are due to difference between versions 1.0 and 1.1
-	IGNORE="^all data is saved in '.*'|^box dimensions: [0-9]+x[0-9]+x[0-9]+|^[0-9]+ :  [0-9]+ [0-9]+ [0-9]+ [0-9]+ [0-9]+ "
-	if [ $MODE == "mpi_seq" ]; then
+    IGNORE="^all data is saved in '.*'|^box dimensions: [0-9]+x[0-9]+x[0-9]+|^[0-9]+ :  [0-9]+ [0-9]+ [0-9]+ [0-9]+ [0-9]+ "
+    if [ $MODE == "mpi_seq" ]; then
       IGNORE="$IGNORE|^(M|Total m|Maximum m)emory usage"
+    elif [ $MODE == "ocl_seq" ]; then
+      IGNORE="$IGNORE|^Found OpenCL device|^Initializing (clFFT|FFTW3)|^(M|Total m)emory usage"  
 	fi
     if [[ $MODE == "mpi" || $MODE == "mpi_seq" ]]; then
       CUT="^Error posting writev, " # due to typical random errors of MPICH under Windows
-	else
-	  CUT=""
-	fi
+    else
+      CUT=""
+    fi
     asmin rtol 4
-	numigndiff $1 $2 "$IGNORE" "$CUT"
+    numigndiff $1 $2 "$IGNORE" "$CUT"
   elif [ "$base" == $SOREF ]; then
     if [[ $MODE == "mpi" || $MODE == "mpi_seq" ]]; then
       CUT="^Error posting writev, " # due to typical random errors of MPICH under Windows
-	else
-	  CUT=""
-	fi
+    else
+      CUT=""
+    fi
     igndiff $1 $2 "^Usage: '.*'|^Type '.*' for details" "$CUT"
   elif [ "$base" == "log" ]; then
     # All parts except the first two are due to difference between versions 1.0 and 1.1
-	IGNORE="^Generated by ADDA v\.|^command: '.*'|^Incident beam: [pP]lane wave|^Polariza(tion|bility) relation: |^Total number of matrix-vector products: "
-	if [ $MODE == "mpi_seq" ]; then
+    IGNORE="^Generated by ADDA v\.|^command: '.*'|^Incident beam: [pP]lane wave|^Polariza(tion|bility) relation: |^Total number of matrix-vector products: "
+    if [ $MODE == "mpi_seq" ]; then
       IGNORE="$IGNORE|^The program was run on: |^(M|Total m|Maximum m)emory usage"
-	fi
-	CUT="^Total wall time: "
-	asmin rtol 4
-	numigndiff $1 $2 "$IGNORE" "$CUT"
+    elif [ $MODE == "ocl_seq" ]; then
+      IGNORE="$IGNORE|^Found OpenCL device|The FFT grid is: [0-9]+x[0-9]+x[0-9]+||^(M|Total m)emory usage"  
+    fi
+    CUT="^Total wall time: "
+    asmin rtol 4
+    numigndiff $1 $2 "$IGNORE" "$CUT"
   elif [[ "$base" =~ "^CrossSec-" ]]; then
     numdiff $1 $2
   elif [[ "$base" =~ "^mueller|^ampl" ]]; then
     asmin atol 9
-	asmin rtol 6
-	numdiff $1 $2
+    asmin rtol 5
+    numdiff $1 $2
   elif [[ "$base" =~ "^log_(int_|orient_avg$)" ]]; then
     asmin atol 13
-	numdiff $1 $2
+    numdiff $1 $2
   elif [[ "$base" == "granules" ]]; then #compare only some comments and total number of lines
     if [ `wc -l < $1` == `wc -l < $2` ]; then
-	  igndiff $1 $2 "^([^#]|#generated by ADDA v\.)"
-	else 
-	  echo "Different number of granules"
-	  return 1
-	fi  
+      igndiff $1 $2 "^([^#]|#generated by ADDA v\.)"
+    else 
+      echo "Different number of granules"
+      return 1
+    fi  
   elif [[ "$base" =~ "^.*\.(geom|dat)$" ]]; then
     igndiff $1 $2 "generated by ADDA v\."
   else
@@ -159,12 +163,12 @@ function mydiff {
   # bring up diff only if files are significantly different (see mycmp above)
   if !(mycmp $1 $2); then
     echo "!!! Difference between files '$1' and '$2'" >&2
-	# !!! This should be adjusted
+    # !!! This should be adjusted
     # It is recommended to put here a GUI diff program, which allows quick estimate of the 
-	# importance of differences (e.g. when there are differences in minor digits of many numbers).
+    # importance of differences (e.g. when there are differences in minor digits of many numbers).
     # However, most effort should be put in improving mycmp, so that calling the function below 
-	# will indicate significant error by itself. The following line can be commented out at all, 
-	# since function mycmp will produce (significant) diff of compared files to stderr.
+    # will indicate significant error by itself. The following line can be commented out at all, 
+    # since function mycmp will produce (significant) diff of compared files to stderr.
     # Options include, for example: tortoisemerge, meld, vimdiff
     tortoisemerge $1 $2
   fi
@@ -205,27 +209,27 @@ fi
 while read -r cmpfiles cmdline; do
   if [[ "$cmpfiles" =~ "^;.*;$" ]]; then
     # process definitions of variables; each variable must be defined only once
-	let imax=imax+1
-	finds[$imax]=$cmpfiles
-	reps[$imax]="$cmdline"
+    let imax=imax+1
+    finds[$imax]=$cmpfiles
+    reps[$imax]="$cmdline"
   #skip blank and commented lines, and all lines when skip=0
   elif [[ -n "$cmpfiles" && "${cmpfiles:0:1}" != "#" && ($skip -eq 0 || ($skip -eq 1 && "$cmdline" =~ "$3")) ]]; then
     skip=0;
-	for i in `seq 0 $imax`; do # variable substitution
-	  cmdline="${cmdline/${finds[$i]}/${reps[$i]}}"
-	done
-	echo $cmdline
+    for i in `seq 0 $imax`; do # variable substitution
+      cmdline="${cmdline/${finds[$i]}/${reps[$i]}}"
+    done
+    echo $cmdline
     # clean up to remove warnings
     rm -f -r $SOREF $SOTEST $DIRREF $DIRTEST
     # reference run
     runref="$EXECREF $cmdline -dir $DIRREF"
-	if !($runref <&3 > $SOREF); then
+    if !($runref <&3 > $SOREF); then
       if $IGNERRREF; then
-	    refok=0
-	  else
-	    echo -e "\nERROR while running \n$runref\nsee $SOREF" >&2
+        refok=0
+      else
+        echo -e "\nERROR while running \n$runref\nsee $SOREF" >&2
         exit 1
-	  fi
+      fi
     else 
       refok=1
     fi
@@ -241,21 +245,21 @@ while read -r cmpfiles cmdline; do
         mv $SOREF $DIRREF/$SONAME
         mv $SOTEST $DIRTEST/$SONAME
         if [ "$cmpfiles" == $ALLNAME ]; then
-		  cmpfiles=`ls $DIRREF`
-		else
-		  cmpfiles="${cmpfiles//,/ }"
-		fi
-    	for file in $cmpfiles; do
+          cmpfiles=`ls $DIRREF`
+        else
+          cmpfiles="${cmpfiles//,/ }"
+        fi
+        for file in $cmpfiles; do
           mydiff "$DIRREF/$file" "$DIRTEST/$file"
         done
       else
         if [[ "$cmpfiles" == $SONAME || "$cmpfiles" == $ALLNAME ]]; then
-		  mydiff $SOREF $SOTEST
+          mydiff $SOREF $SOTEST
         else
           echo "When run directory is not created by ADDA, only $SONAME (or $ALLNAME) can be compared"
           exit 1
         fi
       fi
-	fi
+    fi
   fi
 done < "$SUITEFILE"
