Update for misc/near_field package:
The default compiler is now gfortran. In combination with newer version of MPICH, all previous warnings disappeared in Windows compilation. Therefore Windows executables were updated - Fixes issue 104. 

All test scripts were updated to automatically locate ADDA executable in src/seq folder if $ADDABIN is not set. A few other minor changes to scripts and the manual.

svn properties have been set for files throughout the package.

Another minor update - eol-style for win32/README was set to (always) Windows to make the producing of win32 packages on other systems more reliable.

diff --git a/misc/near_field/RUNTESTS/runall b/misc/near_field/RUNTESTS/runall
--- a/misc/near_field/RUNTESTS/runall
+++ b/misc/near_field/RUNTESTS/runall
@@ -1,10 +1,19 @@
 #!/bin/bash
 
 if [ -z "${ADDABIN}" ]; then
- export ADDABIN=../../../src/adda
+  export ADDABIN=$(readlink -f ../../../src/seq/adda)
+fi
+if [ ! -f "${ADDABIN}" ]; then
+  echo "ERROR: No adda binary was found, as specified by environmental variable ADDABIN='${ADDABIN}'"
+  exit 1
 fi
 if [ -z "${MPIEXEC}" ]; then
- export MPIEXEC="mpirun -np 4"
+  which mpiexec > /dev/null 2>&1 # test availability of mpiexec
+  if [ $? -eq 0 ]; then
+    export MPIEXEC="mpiexec -n 4"
+  else
+    export MPIEXEC=""
+  fi
 fi
 
 for j in *; do
